remote_user: root
galaxy_user: galaxy
galaxy_root: /srv/galaxy
galaxy_server_dir: "{{ galaxy_root }}/server"
galaxy_vcs: git
galaxy_changeset_id: release_17.01 
galaxy_force_checkout: yes
users: galaxy

# MOVED to HOST_VARS
##########################
#miniconda_home: /cvmfs/soft.galaxy/galaxy/tool-dependency/_conda/
#miniconda_modify_path: yes
#miniconda_rcfile: /home/galaxy/.bashrc
#miniconda_installed: yes
#miniconda_lib: "{{ miniconda_home }}/lib"
#
#pip_virtualenv_command: "/cvmfs/soft.galaxy/galaxy/tool-dependency/_conda/bin/virtualenv -p  /cvmfs/soft.galaxy/galaxy/tool-dependency/_conda/bin/python"
#######################

postgresql_objects_users:
  - name: galaxy
    postgresql_login_unix_socket: /srv/sock/postgresql/


postgresql_objects_databases:
  - name: galaxy
    owner: galaxy
    postgresql_login_unix_socket: /srv/sock/postgresql/

postgresql_pg_hba_conf:
  - host  all all  0.0.0.0/0 trust

postgresql_objects_groups: []

postgresql_objects_privileges: []



galaxy_config:
  "app:main":
    database_connection: postgresql:///galaxy?host=/srv/sock/postgresql/
    admin_users: dmorais@galaxy.genap.ca
    tool_dependency_dir: /srv/galaxy/deps
  "uwsgi":
    processes: 1
    socket: 127.0.0.1:4001
    pythonpath: "{{ galaxy_server_dir }}/lib"
    threads: 4
    master: True

nginx_enable_default_server: false
nginx_configs:
  - galaxy

supervisor_configs:
  - galaxy
